### ISSUE TITLE
Support adding scalar date_xx to vector?

### ISSUE THREAD

**Issue by krlmlr** [s-fleck/dint#5]
``` r
dint::date_yq(2020, 1) + 2:3
#> Error in d[, 2] <- d[, 2] + inc: number of items to replace is not a multiple of replacement length
```

<sup>Created on 2020-03-03 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Perhaps `vctrs::vec_recycle()` or `vctrs::vec_recycle_common()` is helpful here.

**Comment by s-fleck** [comment]
thanks for the report! I'm currently on vacation, but I'll look into it when I return home in two weeks.

**Comment by s-fleck** [comment]
I did my own implementation because i want to keep dint base R only, but addition and subtraction should now behave as `vctrs::vec_recycle` (e.g. only scalars are recycled).
